#!/bin/sh
# 
# Usage: script/bootstrap
# 
# Make sure all our local dependencies are satisfied.
# =============================================================================
cd "$(dirname $0)"/..

rm -rf .bundle/config

bundle check --path .bundle > /dev/null 2>&1 ||
  bundle install --binstubs bin --path .bundle --quiet