#!/bin/sh
# 
# Usage: script/release
# 
# Tag and push a release.
# =============================================================================
cd "$(dirname $0)"/..

# Build a new .gem archive
rm -rf shipmate-*.gem
gem build -q shipmate.gemspec

# Make sure we're on the master branch
(git branch | grep -q '* master') || {
  echo "Only release from the master branch."
  exit 1
}

# Figure out what version we're releasing
tag=v`ls shipmate-*.gem | sed 's/shipmate-\(.*\)\.gem$/\1/'`

# Make sure we haven't released this version before
git fetch -t origin

(git tag -l | grep -q "$tag") && {
  echo "Whoops, there's already a '${tag}' tag."
  exit 1
}

# Tag it and bag it
gem push shipmate-*.gem && git tag "$tag" &&
  git push origin master && git push origin "$tag"